---
# Override resource name
#nameOverride

# Override url base path. Default to mutate
#basePathOverride:

# PodNodesSelector   
# Override podnodeselector handler path. Default to pod-nodes-selector
#podNodesSelectorPathOverride: 
# Confiruation for podnodesselector. The namespace and labels are set here following the format:
#   namespace: key=label,key=label; namespace2: key=label
# Note: Multiple namespaces seperate by ;
#
# Examples:
#   devel: node-role.kubernetes.io/development=true, beta.kubernetes.io/instance-type=t3.large
podNodesSelectorConfig:

# Configuration for ignoring pods for podnodesselector. 
# Pods having specified labels will be ignored and nodeSelector field will not be added to them.
# labels are set here following the format:
# key1=val1, key2=val2
# Note: Lables seperate by ,
ignorePodsWithLabels: 

service:
  # the service is important. It forms part of the CN for SSL certificate. 
  name: admission-webhook
  #type: 
  annotations: {}

replicas: 1  

strategy: 
  type: RollingUpdate

image: 082830052325.dkr.ecr.us-east-1.amazonaws.com/devflows/admission-webhook-server
imageTag: v1
imagePullPolicy: Always 
