linters-settings:
  gomnd:
    settings:
      mnd:
        checks: [argument, case,condition,operation,return,assign]
  gocritic:
    disabled-checks:
      - captLocal
      - commentFormatting
      - ifElseChain
      - exitAfterDefer
  funlen:
    lines: 75
    statements: 40
  gosec:
    excludes:
      - G101
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    #- dupl
    #- errcheck
    - exportloopref
    - exhaustive
    - funlen
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    #- stylecheck
    - typecheck
    - unconvert
    #- unparam
    - unused
    - varcheck
    - whitespace
