apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helper.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "helper.labels" . | indent 4}}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "ssl/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "ssl/tls.key" | b64enc }}
