---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "helper.labels" . | indent 4}}
{{- with .Values.service.annotations }}
  annotations:
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
spec:
  selector:
{{- include "helper.labels" . | indent 4}}
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
  - name: https
    port: 443
    targetPort: https

