name: Docker Image CI - import202108

on:
  push:
    branches: ["**"]

jobs:
  setup-build-publish:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build and Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

        # see: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVFLOWS_AWS_ACCESS_KEY_ID_IMPORT202108 }}
          aws-secret-access-key: ${{ secrets.DEVFLOWS_AWS_SECRET_ACCESS_KEY_IMPORT202108 }}
          aws-region: us-east-1
      
      # see: https://github.com/aws-actions/amazon-ecr-login
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compute Tag
        run: |
            SHA=`echo ${GITHUB_SHA} | cut -c1-7`
            echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/}-${SHA} | sed "s/[^[:alnum:]]/-/g")" >> $GITHUB_ENV
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
        run: |
            docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
            docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
            
      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
