name: Go

on:
  push:
    branches: ["**"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          CLUSTER_TOKEN: test
          EKS_API_SERVER: test.svc
          KUBE_CONFIG_MODE: FROM_CLUSTER_TOKEN
        run: go test -v ./...
